[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = "'"
run = "plugin bunny"

[[mgr.prepend_keymap]]
on   = [ "i" ]
run = "plugin searchjump -- autocd"
desc = "searchjump mode"

# chmod.yazi - Change file permissions
[[mgr.prepend_keymap]]
on = [ "c", "m" ]
run = "plugin chmod"
desc = "Chmod on selected files"

# sshfs.yazi - SSHFS integration
[[mgr.prepend_keymap]]
on = [ "M", "s" ]
run = "plugin sshfs -- menu"
desc = "Open SSHFS options"

# compress.yazi - Compress files
[[mgr.prepend_keymap]]
on = [ "c", "a", "a" ]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = [ "c", "a", "p" ]
run = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on = [ "c", "a", "h" ]
run = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on = [ "c", "a", "l" ]
run = "plugin compress -l"
desc = "Archive selected files (compression level)"

# zoom.yazi - Zoom image previews
[[mgr.prepend_keymap]]
on = [ "+" ]
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = [ "-" ]
run = "plugin zoom -1"
desc = "Zoom out hovered file"

# gvfs.yazi - Mount/unmount devices
[[mgr.prepend_keymap]]
on = [ "M", "m" ]
run = "plugin gvfs -- select-then-mount --jump"
desc = "Select device to mount and jump"

[[mgr.prepend_keymap]]
on = [ "M", "R" ]
run = "plugin gvfs -- remount-current-cwd-device"
desc = "Remount device under cwd"

[[mgr.prepend_keymap]]
on = [ "M", "u" ]
run = "plugin gvfs -- select-then-unmount --eject"
desc = "Select device then eject"

[[mgr.prepend_keymap]]
on = [ "M", "U" ]
run = "plugin gvfs -- select-then-unmount --eject --force"
desc = "Select device then force to eject/unmount"

[[mgr.prepend_keymap]]
on = [ "M", "a" ]
run = "plugin gvfs -- add-mount"
desc = "Add a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "M", "e" ]
run = "plugin gvfs -- edit-mount"
desc = "Edit a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "M", "r" ]
run = "plugin gvfs -- remove-mount"
desc = "Remove a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "g", "m" ]
run = "plugin gvfs -- jump-to-device"
desc = "Select device then jump to mount point"

[[mgr.prepend_keymap]]
on = [ "`", "`" ]
run = "plugin gvfs -- jump-back-prev-cwd"
desc = "Jump back to position before jump to device"

# copy-file-contents.yazi - Copy file contents
[[mgr.prepend_keymap]]
on = [ "c", "y" ]
run = "plugin copy-file-contents"
desc = "Copy file contents to clipboard"
